name: Run Jmeter Tests from Config File
on:
  push:
    branches:
      - main
env:
  FOLDER: DeterAPI2,DeterAPI1
  SCRIPTS: script1.sh script2.sh script3.sh

  
jobs:  
  job1-api:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Scripts
        run: |
          echo "Processing folder: $FOLDER"
          for script in $SCRIPTS; do
            script_path="$FOLDER/$script"
            if [ -f "$script_path" ]; then
              bash "$script_path"
            else
              echo "No script found at $script_path"
            fi
          done
      
  #job1-api:
   # runs-on: ubuntu-latest
    
    #steps:
      # checkout repository
     # - name: Checkout repository
      #  uses: actions/checkout@v2

      #- name: Read and process lines from text file
       # run: |
        #  while IFS= read -r line || [ -n "$line" ]; do
         #   
          #  # Further split the folder and scripts
           # IFS='-' read -r folder scripts <<< "$folder_script"
            #
            # Split the scripts into an array
            #IFS=',' read -r -a script_array <<< "$scripts"
            #
            #
            # Navigate to the folder and run each script
            #if [ -d "$folder" ]; then
             # cd "$folder"
              #for script in "${script_array[@]}"; do
               # if [ -f "$script" ]; then
                #  echo "Running script: $script"
                 # bash "$script"
                #else
                 # echo "Script not found: $script"
                #fi
              #done
              #cd -
            #else
             # echo "Folder not found: $folder"
            #fi
          #done < text.txt

     # - name: Read and process lines from text file
     #   run: |
      #    while IFS= read -r line || [ -n "$line" ]; do
      #      # Split the line into components

     # - name: Set up AWS CLI
      #  uses: aws-actions/configure-aws-credentials@v1
       # with:
        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         # aws-region: us-east-1


      #- name: Run Script
       # run: |
        #  echo "Processing folder: ${{ matrix.folder }}"
         #  if [ -f "${{ matrix.folder }}/scripts.sh" ]; then
          #  #bash "${{ matrix.folder }}/script1.sh"
           # #bash "${{ matrix.folder }}/script2.sh"
            #bash "${{ matrix.folder }}/scripts.sh"
             #echo "No script found in ${{ matrix.folder }}"
          #fi

  job2-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [DeterUI]
        scripts: [script1.sh]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/scripts.sh" ]; then
            bash "${{ matrix.folder }}/scripts.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job3-api1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [DeterAPI2]
        scripts: [script1.sh,script2.sh,script3.sh]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/scripts.sh" ]; then
            bash "${{ matrix.folder }}/scripts.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job3-api:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Scripts
        run: |
          echo "Processing folder: $FOLDER"
          for script in $SCRIPTS; do
            script_path="$FOLDER/$script"
            if [ -f "$script_path" ]; then
              bash "$script_path"
            else
              echo "No script found at $script_path"
            fi
          done
      
