name: Run Jmeter Tests from Config File
on:
  push:
    branches:
      - main
  
jobs:  
  job1-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          folder: [DeterAPI1]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/script.sh" ]; then
            bash "${{ matrix.folder }}/script1.sh"
            bash "${{ matrix.folder }}/script2.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job2-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [DeterUI2]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/script.sh" ]; then
            bash "${{ matrix.folder }}/script1.sh"
            bash "${{ matrix.folder }}/script2.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job3-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [DeterAPI2]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/script.sh" ]; then
            bash "${{ matrix.folder }}/script1.sh"
            bash "${{ matrix.folder }}/script2.sh"
            bash "${{ matrix.folder }}/script3.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
